### PR TITLE
Fix ColumnFamilyTest.BulkAddDrop

### LINKED ISSUE #85: Unit test failed
### Expected behavior

```
ctest # execute successfully
```

### Actual behavior

```
97% tests passed, 4 tests failed out of 152

Total Test time (real) = 683.01 sec

The following tests FAILED:
          3 - column_family_test (Subprocess aborted)
         16 - db_compaction_test (Subprocess aborted)
         29 - db_properties_test (SEGFAULT)
         38 - db_wal_test (SEGFAULT)
```

### Steps to reproduce the behavior

As core functionality isn't affected, we just leave the issue here, in hope of someone could help fix this.

### PR DESCRIPTION
**Pull request by v1siuol**
Fix #85 .

```
$ ./column_family_test
[==========] Running 102 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 47 tests from FormatDef/ColumnFamilyTest
[ RUN      ] FormatDef/ColumnFamilyTest.DontReuseColumnFamilyID/0
...
[----------] 4 tests from FormatLatest/FlushEmptyCFTestWithParam (161 ms total)

[----------] Global test environment tear-down
[==========] 102 tests from 4 test cases ran. (29366 ms total)
[  PASSED  ] 102 tests.
```

Not an expert on c++, but I think there is some memory issues in the currect bulk CreateColumnFamilyImpl.
```
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./column_family_test --gtest_filter=FormatDef/ColumnFamilyTest.BulkAddDrop*
```

Example that simulates the change of behaviors in this pr
```
void test_vectorp() {
  autovector<double*> array;
  auto cleanup_func = [&]() {
    for (const auto& e : array) {
      delete e;
    }
  };
  int lmt = 100;
  // for (int i = 0; i < lmt; ++i) {
  //   double* pd = new double(1);  // ok, but need to clean up
  //   array.emplace_back(pd);
  // }
  std::vector<double> vd;
  for (int i = 0; i < lmt; ++i) {
    vd.emplace_back();  // bad: heap-use-after-scope
    array.emplace_back(&vd.back());
  }
  double sum = 0;
  for (const auto& e : array) {
    sum += *e;
  }
  cleanup_func();
  std::cout << sum << std::endl;
}
```

Not a big fan of raw pointer (new) either, we might replace it with `autovector<std::unique_ptr>` (which might need to change some interfaces though), open to discuss.

### CODE REVIEW

File: db/db_impl.cc [hunk 1]
```diff
@@ -2195,20 +2200,20 @@ autovector<Status> DBImpl::CreateColumnFamilyImpl(
...
-      edit.SetComparatorName(cf_options[i]->comparator->Name());
-      edit_vec[i].mopt = MutableCFOptions(*cf_options[i], env_);
+      edit_ptr->SetColumnFamily(new_id);
+      edit_ptr->SetLogNumber(logfile_number_);
+      edit_ptr->SetComparatorName(cf_options[i]->comparator->Name());
+      const MutableCFOptions* const mopt_ptr =
+          new MutableCFOptions(*cf_options[i], env_);
 
       cfds.emplace_back(nullptr);
-      mutable_cf_options_list.emplace_back(&edit_vec.back().mopt);
```
Comment (skyzh) [inline db/db_impl.cc:2209]: It is true that this line would place pointers to heap variables in another vector. However, when this function returns,  destructor of `edit_list` is called, which cleans up memory for several `autovector<VersionEdit*>`s, and ultimately cleans up memory for `VersionEdit*`. Note that in C++, dropping a pointer won't call `delete` of the content. e.g.

```
{
  std::vector<int*> x;
  {
    int a = 1;
    x.push_back(&a);
  }
    x.push_back(new int(1));
}
```

This code should run without any error, except `new int(1)` is leaked. So does this part of code.

**Review by skyzh — COMMENTED** [review]
As far as I could see, there should be no memory issue in previous codebase. Would you please share the valgrind output before and after this change?

File: db/db_impl.cc (hunk 1 above)
Comment (v1siuol) [reply db/db_impl.cc:2209]: In your code snippet, you construct `a` inside the block and store its pointer to `x`. After the block (outside the block), `a` is destructed. `x` still has that address, which points to 👻  (UB). You should see errors if you try to access `*x[0]` (e.g., `std::cout << *x[0] << std::endl;`) after the block with ASAN check (note valgrind might not catch this). Reference: https://github.com/google/sanitizers/wiki/AddressSanitizerExampleUseAfterScope

Comment (v1siuol) [reply db/db_impl.cc:2209]: Attach valgrind report - https://gist.github.com/v1siuol/a39e9ec79522763f46ce379a8773bb97

There are two files: `valgrind-before.txt` is the output before the change, and  `valgrind-after.txt` is the output after the change. They are quite verbose and get truncated (you can download them.)

As you can see from the `valgrind-after.txt`, we still have reachable blocks and errors, even though we can pass the test :(

Comment (v1siuol) [reply db/db_impl.cc:2209]: Sharing the process when I was debugging:
```
Thread 1 "column_family_t" hit Breakpoint 2, terarkdb::DBImpl::CreateColumnFamilyImpl (this=0x7ffff6312000, cf_options=...,
    column_family_name=..., handle=...) at <cwd>/db/db_impl.cc:2215
2215          ++ok_count;
(gdb) p *edit_lists[71][0]
$8 = {max_level_ = 0, comparator_ = "leveldb.BytewiseComparator", log_number_ = 3, prev_log_number_ = 0, next_file_number_ = 0,
  max_column_family_ = 0, min_log_number_to_keep_ = 0, last_sequence_ = 0, has_comparator_ = true, has_log_number_ = true,
  has_prev_log_number_ = false, has_next_file_number_ = false, has_last_sequence_ = false, has_max_column_family_ = false,
  has_min_log_number_to_keep_ = false, deleted_files_ = std::set with 0 elements, new_files_ = std::vector of length 0, capacity 0,
  apply_callback_vec_ = {num_stack_items_ = 0, values_ = {{callback = 0x0, args = 0x0}, {callback = 0x0, args = 0x0}},
    vect_ = std::vector of length 0, capacity 0}, column_family_ = 72, is_column_family_drop_ = false, is_column_family_add_ = true,
  column_family_name_ = "cf1-72", is_open_db_ = false, is_in_atomic_group_ = false, remaining_entries_ = 0}
(gdb) c
Continuing.

Thread 1 "column_family_t" hit Breakpoint 3, terarkdb::DBImpl::CreateColumnFamilyImpl (this=0x7ffff6312000, cf_options=...,
    column_family_name=..., handle=...) at <cwd>/db/db_impl.cc:2220
2220        if (ok_count > 0) {  // write thread
(gdb) p *edit_lists[71][0]
$9 = {max_level_ = 0, comparator_ = "leveldb.BytewiseComparator", log_number_ = 0, prev_log_number_ = 1,
  next_file_number_ = 140737323541376, max_column_family_ = 0, min_log_number_to_keep_ = 0, last_sequence_ = 0, has_comparator_ = true,
  has_log_number_ = true, has_prev_log_number_ = false, has_next_file_number_ = false, has_last_sequence_ = false,
  has_max_column_family_ = false, has_min_log_number_to_keep_ = false, deleted_files_ = std::set with 0 elements,
  new_files_ = std::vector of length 549755170085, capacity 0 = {<error reading variable>
```
Reference: https://github.com/bytedance/terarkdb/blob/d4509bd51038b3618dc043bd3b1e20dea2b2921d/db/db_impl.cc#L2215-L2220

The first access is in the block (db_impl.cc:2215), everything looks good.

But the second access is outside the block (db_impl.cc:2220), boom.

Comment (skyzh) [reply db/db_impl.cc:2209]: > In your code snippet, you construct `a` inside the block and store its pointer to `x`. After the block (outside the block), `a` is destructed. `x` still has that address, which points to 👻 (UB). You should see errors if you try to access `*x[0]` (e.g., `std::cout << *x[0] << std::endl;`) after the block with ASAN check (note valgrind might not catch this). Reference: https://github.com/google/sanitizers/wiki/AddressSanitizerExampleUseAfterScope

Agree on this. When I was reviewing the code, I didn't realize that there is a thread reading from the vector. Now this looks reasonable to me.

**Comment by skyzh** [comment]
cc @yapple Would you please take a look?

**Review by skyzh — APPROVED** [review]
After some internal discussions, we observed that this could be solved by simply reserve enough space for `edit_vec` (now `context_vec`). So @mm304321141 proposed another way to fix and added a new commit to your branch.

The underlying problem is not because of use pointer outside block. When `autovector` gets new elements, the underlying content might be moved to another place. Therefore, by reserving enough space, we could solve this issue.

~~It is true that pushing pointer to vector elements to another vector is a bad thing, but we decided to go simple here.~~

Another benefit of current fix is that, we do not need to call malloc / free for every CF.

After all, many thanks for your contribution!
